{{/*
   * Copyright 2022 Open Ag Data Alliance
   *
   * Licensed under the Apache License, Version 2.0 (the "License");
   * you may not use this file except in compliance with the License.
   * You may obtain a copy of the License at
   *
   *     http://www.apache.org/licenses/LICENSE-2.0
   *
   * Unless required by applicable law or agreed to in writing, software
   * distributed under the License is distributed on an "AS IS" BASIS,
   * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   * See the License for the specific language governing permissions and
   * limitations under the License.
   */}}
{{- range .Values.oada.users -}}
{{- $secretName := print "user-" .name "-" $.Release.Name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app.kubernetes.io/name: {{ $.Chart.Name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    {{- include "oada.chart.labels" $ | nindent 4 }}
stringData:
  {{/* Generate random password */}}
  password: {{ randAlphaNum 20 }}
  {{/* Generate random token */}}
  {{- $token := uuidv4 -}}
  token: {{ $token }}
  header: >
    Authorization: Bearer {{ $token }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: user-add-{{ .name }}-{{ $.Release.Name }}
  labels:
    app.kubernetes.io/name: {{ $.Chart.Name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    {{- include "oada.chart.labels" $ | nindent 4 }}
spec:
  backoffLimit: 10
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: user-add
          envFrom:
            - configMapRef:
                name: {{ $.Chart.Name }}-configmap-{{ $.Release.Name }}
          env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: password
          image: oada/users:{{ $.Values.oada.tag }}
          imagePullPolicy: {{ $.Values.global.development | ternary "Always" "IfNotPresent" }}
          command: ["/usr/bin/dumb-init", "--rewrite", "15:2", "--", "/bin/sh"]
          args: ["-c", "yarn workspace @oada/users run add -u {{ .name }} -p ${PASSWORD} -a {{ .admin }} "]
      containers:
        - name: token-create
          envFrom:
            - configMapRef:
                name: {{ $.Chart.Name }}-configmap-{{ $.Release.Name }}
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: token
          image: oada/users:{{ $.Values.oada.tag }}
          imagePullPolicy: {{ $.Values.global.development | ternary "Always" "IfNotPresent" }}
          command: ["/usr/bin/dumb-init", "--rewrite", "15:2", "--", "/bin/sh"]
          args: ["-c", "yarn workspace @oada/auth run token create -u {{ .name }} -s {{ .scope }} ${TOKEN} "]
{{- end -}}